// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbtBz4OdG62bV1vbugOF0-6koeGBvpCBU',
    appId: '1:894532107300:web:aaf292a1c78518208eacb1',
    messagingSenderId: '894532107300',
    projectId: 'Dimyappoficial',
    authDomain: 'Dimyappoficial.firebaseapp.com',
    storageBucket: 'Dimyappoficial.appspot.com',
    measurementId: 'G-9RN8TZG6B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_LKydm8aS4ld0Pq6ioFl6an0DAU4RaQ',
    appId: '1:1024433973403:android:bef1dbea002660d9b3fe3e',
    messagingSenderId: '1024433973403',
    projectId: 'Dimy',
    storageBucket: 'Dimy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2uZOtIouUpEop6VVRy3X2kBeRLkPDenk',
    appId: '1:1024433973403:ios:78262981fdd8e90fb3fe3e',
    messagingSenderId: '1024433973403',
    projectId: 'Dimy',
    storageBucket: 'Dimy.appspot.com',
    iosBundleId: 'com.Dimy.oficial',
  );

}